### ISSUE TITLE
Числа лучше хранить как числа

### ISSUE THREAD

**Issue by coursar** [greatschemer/tariffs#3]
https://github.com/greatschemer/tarrifs/blob/f4cb11796a9bfbe422731f3c06a6d47816e84c8f/src/App.js#L34-L35

**Comment by greatschemer** [comment]
пофикшено!

**Comment by coursar** [comment]
Зачем открывать? Если сделали - надо закрывать issue.

**Comment by coursar** [comment]
Достаточно того, что вы коммитом закроете issue (не надо писать комментарии) - см.видео по гиту.
